### PR TITLE
New Features

### PR DESCRIPTION
**Pull request by ahmadpak**
We need to customise the Sales invoice and PoS feature (both inbuilt PoS and PoS Awesome) to accomodate the use of store credits in retail environment.

A customer can have store credits as a result of any of the following incidences;

1. Customer returns an item and the value is put in the customer’s account for use during the next purchase
2. Customer makes purchase of NGN900 and pays NGN1,000. He has change of N100 but asks that this change be put in his account for subsequent use
3. Customer does an exhange of product X for Product Y. X is more expensive than Y so customer has change. He asks for this to be put in his account for use in his next visit

At the moment ERPNext is totally incapable of handling any of this scenario in a seamless manner. This is very puzzling to users who are unable to understand how these very basic retail tasks that even the most basic of retail software handle easily is totally missing in ERPNext.

We need **to fix this.**

The main challenges in ERPNext that makes these functions impossible are

1. There is no option to use available store credit when creating a new sales invoice. None. I was thinking unused credit notes should show up in the “advance payments” table alongside payment entires. This is not the case.
2. There is no option to convert customer change to store credit or a form of credit note during sales invoicing. None. In ERPNext a customer’s change is automatically assumed to be returned to the customer or written off to P&L
3. More importantly it is not possible to have a sale and a return on the same invoice. This basically is the concept of a customer exchange. You return one item while buying another and the difference in prices (if any) is settled. This is not possible in ERPNext at the moment.

Like I said we are trying to make all these possible by customising the Sales Invoice and PoS documents.

### CODE REVIEW

**Comment by olamide2** [comment]
Thank you Ahmad for the hard work on this

Hope this can be merged soon

@yrestom if there is any issue let us know ASAP.

Thanks guys

**Comment by yrestom** [comment]
Merged int develop branch https://github.com/yrestom/POS-Awesome/commits/develop
Thank you

**Comment by yrestom** [comment]
@faisal-tech-ninja 
on submit invoice using "Use Customer Credit" I am getting this error:

`Traceback (most recent call last):
  File "/home/frappe/bench-13/apps/frappe/frappe/app.py", line 64, in application
    response = frappe.api.handle()
  File "/home/frappe/bench-13/apps/frappe/frappe/api.py", line 58, in handle
    return frappe.handler.handle()
  File "/home/frappe/bench-13/apps/frappe/frappe/handler.py", line 30, in handle
    data = execute_cmd(cmd)
  File "/home/frappe/bench-13/apps/frappe/frappe/handler.py", line 70, in execute_cmd
    return frappe.call(method, **frappe.form_dict)
  File "/home/frappe/bench-13/apps/frappe/frappe/__init__.py", line 1113, in call
    return fn(*args, **newargs)
  File "/home/frappe/bench-13/apps/posawesome/posawesome/posawesome/api/posapp.py", line 386, in submit_invoice
    jv_doc.save()
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 285, in save
    return self._save(*args, **kwargs)
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 307, in _save
    self.insert()
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 238, in insert
    self.run_before_save_methods()
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 947, in run_before_save_methods
    self.run_method("validate")
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 848, in run_method
    out = Document.hook(fn)(self, *args, **kwargs)
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 1133, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 1116, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/frappe/bench-13/apps/frappe/frappe/model/document.py", line 842, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/frappe/bench-13/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 44, in validate
    self.validate_reference_doc()
  File "/home/frappe/bench-13/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 329, in validate_reference_doc
    self.validate_invoices()
  File "/home/frappe/bench-13/apps/erpnext/erpnext/accounts/doctype/journal_entry/journal_entry.py", line 373, in validate_invoices
    frappe.throw(_("{0} {1} is not submitted").format(reference_type, reference_name))
  File "/home/frappe/bench-13/apps/frappe/frappe/__init__.py", line 409, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red', is_minimizable=is_minimizable, wide=wide, as_list=as_list)
  File "/home/frappe/bench-13/apps/frappe/frappe/__init__.py", line 388, in msgprint
    _raise_exception()
  File "/home/frappe/bench-13/apps/frappe/frappe/__init__.py", line 342, in _raise_exception
    raise raise_exception(msg)
frappe.exceptions.ValidationError: Sales Invoice ACC-SINV-2021-00060 is not submitted
`

Screen Shot 2021-03-29 at 22 22 17
Screen Shot 2021-03-29 at 22 22 31
Screen Shot 2021-03-29 at 22 21 55

**Comment by yrestom** [comment]
@faisal-tech-ninja  Please let the next PR against develop repo

**Comment by faisal-zahoor** [comment]
@yrestom can you tell me the process to regenerate this error?

**Comment by faisal-zahoor** [comment]
> @faisal-tech-ninja Please let the next PR against develop repo

ok, i will

**Comment by yrestom** [comment]
> can you tell me the process to regenerate this error?

As you see from the last image, I am trying to pay an invoice using customer credit with a cash payment, and the invoice has a discount.

**Comment by CloudERPng** [comment]
@ahmadpak @faisal-zahoor Can you please look at resolving the bugs above

1. The paying an invoice using customr credit and a cash payment where the invoice has a pricing rule discount throws up that bug, please test and let us see how we can sort it out
2. The receipt print format bug posted by @CloudERPng above.

Thank you

**Pull request closed without merging**
