### PR TITLE
POS Closing Shift Credit sale total

### PR DESCRIPTION
**Pull request by Vijitha1983**
I need add the day credit sales amount to the POS Closing shift report, could please leave a comment how it it possible 

if it is possible please advice how do it with path and code

### CODE REVIEW

**Comment by yrestom** [comment]
@Vijitha1983 
Can you add more details about what you want to achieve and maybe some screenshot

**Comment by Vijitha1983** [comment]
Thank you for your reply. here i attached POS Closing shift report for your refence, and summary as follows

Total Sales                         400.00
Cash                                  -100.00
Credit Card                       -200.00

and there are some balance i need to show in the report it is credit sales value , also let me is there are any option to get "X" report before day end
image

**Comment by yrestom** [comment]
@Vijitha1983  POS Closing Shift is a typical Frappe Doctype so you can use the normal ways to customize it, like add custom field or add server script or client script to populate any data required

**Comment by yrestom** [comment]
@Vijitha1983 Please next time create an issue instead of pull request

**Pull request closed without merging**
